version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: leetcode_build
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: leetcode
    ports:
      - "5433:5432"
    volumes:
      - leetcode_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  leetcode_db_data: